# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_living', models.FloatField()),
                ('area_total', models.FloatField()),
                ('room_count', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BoodCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('geo_office', models.CharField(max_length=1024)),
                ('ceo', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('location', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('time_ready', models.DateField()),
                ('geo', models.CharField(max_length=1024)),
                ('bood_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BoodCompany')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.District')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
